import React, { useContext } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { MyContext } from "../../../../../../Global/context";

const VideoDescription = () => {
    const {id, darkscheme} = useContext(MyContext);

    return(
        <View style={[styles.container, {backgroundColor: darkscheme ? "#181a20" : "#fbfbfb",}]}>
            <ScrollView showsVerticalScrollIndicator={false}>
                {id == 1 ? <View>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>Python is a high-level programming language that is widely used for a variety of purposes, including software development, data analysis, automation, web development, and artificial intelligence. Learning Python has several objectives, including:</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>1. Building fundamental programming skills: Python is an excellent language for beginners to learn programming basics such as variables, functions, loops, and data structures.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>2. Developing web applications: Python is used for developing web applications and frameworks like Flask and Django.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>3. Enhancing Data Science Skills: Python has become a popular language for data science, and it's used in a variety of industries for analyzing and manipulating large datasets.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>4. Artificial Intelligence and Machine Learning: Python has become one of the most popular languages for artificial intelligence and machine learning, and is used for developing algorithms and models for predictive analysis, data mining, and more.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>5. Game Development: Python is also used for developing video games, and popular game engines like Pygame are built on top of the language.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>Overall, learning Python is useful for anyone who wants to develop versatile programming skills and open up career opportunities in software development, data science, artificial intelligence, automation, and more. It's also a great language for hobbyists and those who want to build their own tools and applications.</Text>
                </View> :
                id == 2 ? <View>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>Java is one of the most popular programming languages in the world, with a wide range of applications and uses. The objectives of learning Java can vary depending on the individual's goals and intended use of the language. Here are some common objectives of learning Java:</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>1. Building fundamental programming skills: Java is an excellent language for learning programming basics such as variables, functions, loops, and data structures.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>2. Developing enterprise applications: Java is widely used for developing enterprise-level applications and systems due to its scalability, portability, and robustness.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>3. Android Development: Java is used for developing Android applications, one of the most popular mobile operating systems.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>4. Web Development: Java is also widely used for developing web applications, and popular frameworks like Spring and Hibernate are built on top of the language.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>5. Data Science and Big Data: Java is used in big data and data science environments for processing and analyzing large datasets.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>6. Game Development: Java is also used for developing video games, and popular game engines like jMonkeyEngine are built on top of the language.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>Overall, learning Java can help individuals develop versatile programming skills and open up many career opportunities in software development, web development, Android development, data science, big data, game development, and more.</Text>
                </View> : 
                id == 3 ? <View>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>Blender is a powerful open-source 3D creation software that can be used to create anything from simple models to complex animated movies. The objectives of learning Blender can vary depending on the individual's goals and intended use of the software. However, some common objectives of learning Blender include:</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>1. 3D Modeling: Blender is widely used for creating 3D models for various purposes, including video games, animation, and product design.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>2. Animation: Blender has a robust set of animation tools that can be used to create complex animations, such as character animations, motion graphics, and visual effects.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>3. Visual Effects: Blender can be used to create visual effects for film and video, such as explosions, smoke, and fire.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>4. Product Visualization: Blender can be used to create high-quality 3D renderings and visualizations of products, which can be useful for advertising and marketing purposes.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>5. Architectural Visualization: Blender can also be used to create architectural visualizations, such as virtual tours of buildings and structures.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>6. Game Development: Blender has a game engine that can be used for developing video games, making it a versatile tool for game developers.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>Overall, learning Blender can help individuals develop versatile 3D creation skills and open up many career opportunities in animation, game development, product design, architectural visualization, and more.</Text>
                </View> :
                id == 4 ? <View>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>The objectives of learning blockchain, a decentralized and secure digital ledger technology, are numerous and varied. Some of the primary objectives of learning blockchain are as follows:</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>1. Understanding the underlying technology: Learning blockchain enables individuals to understand how the technology works and how it can be used in various applications.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>2. Developing skills for blockchain development: Blockchain development is a growing field, and learning blockchain can help individuals develop skills in programming languages such as Solidity, which is used for developing smart contracts on blockchain platforms like Ethereum.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>3. Building decentralized applications: Blockchain technology can be used for building decentralized applications that operate without the need for intermediaries, which can increase transparency and reduce costs.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>4. Understanding the potential for disruption: Learning blockchain can help individuals understand the potential for disruption in various industries, such as finance, healthcare, and supply chain management.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>5. Exploring new business models: Blockchain technology has the potential to create new business models that are more efficient, transparent, and secure.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>6. Enhancing cybersecurity skills: Blockchain technology is designed to be secure, and learning blockchain can help individuals develop skills in cybersecurity, cryptography, and data protection.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>Overall, learning blockchain can open up many opportunities in various industries and enable individuals to develop skills in a growing field that has the potential to revolutionize the way we interact with technology and conduct business.</Text>
                </View> :
                id == 5 ? <View>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>React Native is a popular open-source framework for developing cross-platform mobile applications. Here are some objectives of learning React Native:</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>1. Cross-platform development: One of the key objectives of React Native is to allow developers to build applications that can run on both iOS and Android devices. This can save a significant amount of time and effort compared to building separate apps for each platform.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>2. Code reusability: React Native uses a single codebase for both iOS and Android applications, which means developers can write code once and use it across multiple platforms. This can save development time and resources and make the process more efficient.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>3. Fast development: React Native provides a range of pre-built components that can be used to build UIs, which can speed up the development process.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>4. Native performance: React Native uses native components for rendering, which can provide a better performance compared to other cross-platform frameworks.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>5. Growing demand: React Native has gained popularity among developers, and there is a growing demand for developers who have experience with the framework. Learning React Native can open up career opportunities in mobile app development.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>Overall, learning React Native can help developers create high-quality, cross-platform mobile applications in a fast and efficient manner, while also opening up career opportunities in the mobile app development industry.</Text>
                </View> :
                id == 6 ? <View>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>Learning Photoshop, a powerful and versatile image editing software, can help individuals achieve a range of objectives related to graphic design, photography, and digital media production. Here are some of the main objectives of learning Photoshop:</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>1. Image Editing: One of the primary objectives of learning Photoshop is to develop image editing skills. With Photoshop, users can manipulate images, remove unwanted objects, and adjust color and lighting to create stunning visuals.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>2. Graphic Design: Photoshop is a popular tool for graphic designers, and learning it can help individuals develop skills in creating logos, business cards, flyers, and other design materials.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>3. Photography: Photoshop is also an essential tool for photographers, allowing them to enhance images, correct color and exposure, and apply creative effects to their photos.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>4. Digital Art: Photoshop is a favorite tool of digital artists, allowing them to create original art, designs, and illustrations using the software's wide range of brushes, filters, and other features.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>5. Video Production: Photoshop's capabilities extend to video production, where users can create motion graphics, titles, and special effects.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>Overall, learning Photoshop can be beneficial for individuals seeking to develop their image editing, graphic design, photography, digital art, and video production skills. It is an essential tool for professionals in many industries, including advertising, media, and entertainment.</Text>
                </View> :
                id == 7 ? <View>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>The objectives of learning data science are numerous, as the field has become an integral part of many industries and organizations in recent years. Some common objectives of learning data science include:</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>1. Analyzing and interpreting data: Data science involves using statistical and analytical methods to extract insights from data, which can help businesses make informed decisions and identify patterns and trends.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>2. Developing predictive models: Data science is often used to develop models that can predict future outcomes based on historical data.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>3. Improving business operations: By analyzing data, data scientists can identify areas where businesses can improve their operations, such as reducing costs, improving efficiency, and increasing revenue.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>4. Innovating new products and services: Data science can also be used to identify new product or service opportunities based on customer behavior and preferences.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>5. Enhancing marketing and advertising: Data science can help businesses develop more effective marketing strategies and personalized advertising based on customer data.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>6. Advancing scientific research: Data science is also used in scientific research to analyze and interpret data in fields such as genomics, neuroscience, and ecology.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>Overall, learning data science can help individuals develop skills in statistics, programming, and data analysis, and open up a wide range of career opportunities in fields such as data analysis, machine learning, artificial intelligence, and more.</Text>
                </View> :
                id == 8 ? <View>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>The objectives of learning digital marketing include:</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>1. Acquiring knowledge of digital marketing strategies: Digital marketing encompasses a wide range of strategies such as SEO, PPC, social media marketing, email marketing, content marketing, and more. Learning digital marketing will provide individuals with an understanding of these different strategies and how to implement them effectively.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>2. Building marketing skills for the digital age: Digital marketing requires a different set of skills than traditional marketing, and learning digital marketing will help individuals acquire skills in areas such as data analysis, digital media planning, and social media management.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>3. Developing a competitive advantage: In today's digital age, businesses must have a strong online presence to remain competitive. Learning digital marketing can give individuals and businesses a competitive edge by enabling them to develop effective digital marketing strategies and campaigns.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>4. Building a career in digital marketing: The digital marketing industry is growing rapidly, and there is a high demand for skilled digital marketing professionals. Learning digital marketing can lead to a fulfilling career in a rapidly growing industry.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>5. Understanding customer behavior: Digital marketing provides valuable insights into customer behavior, preferences, and trends. Learning digital marketing can help individuals gain a deeper understanding of customer behavior, which can be applied to develop effective marketing campaigns and strategies.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>Overall, learning digital marketing can provide individuals with valuable skills and knowledge to succeed in today's digital age, and open up many career opportunities in the digital marketing industry.</Text>
                </View> :
                id == 9 ? <View>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>Learning about cybersecurity is becoming increasingly important in today's digital age. Some objectives of learning cybersecurity include:</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>1. Understanding Cyber Threats: One of the main objectives of cybersecurity training is to teach individuals about different types of cyber threats and how they operate. This includes topics such as phishing attacks, malware, ransomware, social engineering, and more.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>2. Protecting Information: Another important objective is to learn how to protect sensitive information such as personal data, financial information, and intellectual property. Cybersecurity training can help individuals learn about security best practices, data encryption, and secure communication protocols.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>3. Managing Security Risks: Cybersecurity training can also teach individuals how to identify and manage security risks within an organization. This includes developing security policies, monitoring network activity, and implementing security controls.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>4. Incident Response: Cybersecurity training can help individuals learn how to respond to security incidents such as data breaches, hacking attempts, and other cyber threats.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>5. Career Advancement: Learning cybersecurity can also open up many career opportunities in various fields such as information technology, government, law enforcement, and consulting.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>Overall, the objectives of learning cybersecurity are to develop skills that help individuals protect themselves and their organizations from cyber threats, manage security risks, and advance their careers in the field of information security.</Text>
                </View> :
                id == 10 ? <View>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>Frontend web development involves creating the user-facing part of a website, including the layout, design, and functionality that users interact with. The objectives of learning frontend web development can vary depending on the individual's goals and intended use of the skills, but some common objectives include:</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>1. Building foundational programming skills: Learning frontend web development can help individuals develop a solid foundation in HTML, CSS, and JavaScript, which are essential languages for creating web applications.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>2. Creating engaging and user-friendly websites: The focus of frontend web development is on creating interfaces that are intuitive, responsive, and visually appealing to users, which can enhance user experience.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>3. Developing skills in web design and user experience (UX) design: Frontend web development involves working closely with designers to bring their designs to life and optimize the user experience.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>4. Building a career in web development: Frontend web development skills are in high demand, and learning these skills can open up many career opportunities in the tech industry.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>5. Understanding web technologies: Learning frontend web development can help individuals understand how web technologies work and how different parts of a website interact with each other.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>Overall, learning frontend web development can help individuals develop versatile programming skills and open up many career opportunities in software development, user experience design, and more.</Text>
                </View> :
                id == 11 ? <View>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>Backend web development refers to the server-side programming that enables the functionality of websites and web applications. The objectives of learning backend web development include:</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>1. Building scalable and robust web applications: By understanding how the backend works, developers can build applications that can handle a large number of users and traffic without crashing or slowing down.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>2. Enhancing web security: Backend developers are responsible for implementing security measures such as authentication, encryption, and access controls to protect user data and prevent unauthorized access.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>3. Integrating databases and APIs: Backend developers work with databases and APIs to store and retrieve data, allowing web applications to access and manipulate data in real-time.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>4. Creating RESTful APIs: RESTful APIs allow frontend developers to easily communicate with the backend, enabling the creation of more interactive and responsive web applications.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>5. Improving website performance: Backend developers can optimize website performance by reducing load times, implementing caching techniques, and optimizing code.</Text>
                    <Text style={[styles.contentPara, {color: darkscheme ? "#ffffffcc" : "#5e5e5e", }]}>Overall, learning backend web development provides individuals with a solid foundation in server-side programming, database management, and security. These skills are essential for building modern web applications that are scalable, secure, and efficient.</Text>
                </View> : <Text>No Content Found!</Text>}
            </ScrollView>
        </View>
    )
}

const styles = StyleSheet.create({
    container:{
        paddingHorizontal: 10,
        height: "100%",
    },
    contentPara:{
        marginTop: 15,
        fontSize: 15,
        textAlign: "justify",
        fontFamily: "Inder-Regular",
    },
})

export default VideoDescription;