const allVideos = [
    {
        banner: "https://sec-art.net/wp-content/uploads/2021/09/python.jpeg",
        video: "eWRfhZUzrAc",
        id: 1,
        title: "Python for Beginners",
        tutor: "Beau Carnes",
        likes: "22 k",
        views: "7 L",
        duration: '4.5 Hrs',
    },
    {
        banner: "https://balasubramanyamlanka.com/posts/java/clone-java-lang-object-clone-method-of-object-class/images/java-banner.jpeg",
        video: "BGTx91t8q50",
        id: 2,
        title: "Java for Beginners",
        tutor: "Navin Reddy",
        likes: "12 k",
        views: "4 L",
        duration: "12.5 Hrs",
    },
    {
        banner: "https://images.macrumors.com/t/7e_Qw4lkjXctGWXTYSueRxsFHcg=/800x0/article-new/2021/10/blender-banner.jpeg?lossy",
        video: "g2U0MiZSV9A",
        id: 3,
        title: "Learning Blender from Scratch",
        tutor: "Tim: ChamferZone",
        likes: "10 k",
        views: "4.3 L",
        duration: "2.25 Hrs",
    },
    {
        banner: "https://as1.ftcdn.net/v2/jpg/04/35/10/18/1000_F_435101823_jottowrJG1OG4gbM2r26VTrvxFSg8yBi.jpg",
        video: "SyVMma1IkXM",
        id: 4,
        title: "Blockchain in 4 Hrs",
        tutor: "Sandeep: Simplilearn",
        likes: "3.4 k",
        views: "1.7 L",
        duration: "4 Hrs",
    },
    {
        banner: "https://process.fs.teachablecdn.com/ADNupMnWyR7kCWRvm76Laz/resize=width:705/https://www.filepicker.io/api/file/4C6yPDywSUeWYLyg1h9G",
        video: "ANdSdIlgsEw",
        id: 5,
        title: "React Native: from Scratch",
        tutor: "Mahdi Sharifimehr",
        likes: "8.6 k",
        views: "5.1 L",
        duration: "6.75 Hrs",
    },
    {
        banner: "https://www.webmarketing-com.com/wp-content/uploads/2022/06/alternative-photoshop-1024x576.jpg.webp",
        video: "IyR_uYsRdPs",
        id: 6,
        title: "Photoshop for Beginners",
        tutor: "Dan Scott",
        likes: "2.4 L",
        views: "1.2 C",
        duration: "3 Hrs",
    },
    {
        banner: "https://www.simplilearn.com/ice9/free_resources_article_thumb/what_is_Data_Science.jpg",
        video: "d0bIgigcOQM",
        id: 7,
        title: "Full Data Science Course",
        tutor: "Rune",
        likes: "12 k",
        views: "6.6 L",
        duration: "12 Hrs",
    },
    {
        banner: "https://digitalcatalyst.in/blog/wp-content/uploads/2022/03/major-components-of-digital-marketing.png",
        video: "hiEb1m7CXH4",
        id: 8,
        title: "Digital Marketing: For Beginners",
        tutor: "Edureka",
        likes: "18 k",
        views: "7.8 L",
        duration: "7.5 Hrs",
    },
    {
        banner: "https://punemirror-dev.s3.ap-south-1.amazonaws.com/full/4ad30cdd-5db9-4bd8-9409-fa48fbaa02dc.jpeg",
        video: "fNzpcB7ODxQ",
        id: 9,
        title: "Cyber Security in 12 Hrs",
        tutor: "Heath Adams",
        likes: "1.1 L",
        views: "33 L",
        duration: "12.25 Hrs",
    },
    {
        banner: "https://i.ytimg.com/vi/7C4dv8vuwEk/maxresdefault.jpg",
        video: "zJSY8tbf_ys",
        id: 10,
        title: "Frontend Development Bootcamp",
        tutor: "Zach Golwitzer",
        likes: "38 k",
        views: "9.9 L",
        duration: "12.25 Hrs",
    },
    {
        banner: "https://www.freecodecamp.org/news/content/images/size/w2000/2021/06/backendpython.png",
        video: "jBzwzrDvZ18",
        id: 11,
        title: "Backend Development Bootcamp",
        tutor: "Tommy",
        likes: "36 k",
        views: "13 L",
        duration: "10.25 Hrs",
    },
]
const allFeaturedVideos = [
    {
        banner: "https://process.fs.teachablecdn.com/ADNupMnWyR7kCWRvm76Laz/resize=width:705/https://www.filepicker.io/api/file/4C6yPDywSUeWYLyg1h9G",
        video: "ANdSdIlgsEw",
        id: 5,
        title: "React Native: from Scratch",
        tutor: "Mahdi Sharifimehr",
        likes: "8.6 k",
        views: "5.1 L",
        duration: "6.75 Hrs",
    },
    {
        banner: "https://sec-art.net/wp-content/uploads/2021/09/python.jpeg",
        video: "eWRfhZUzrAc",
        id: 1,
        title: "Python for Beginners",
        tutor: "Beau Carnes",
        likes: "22 k",
        views: "7 L",
        duration: '4.5 Hrs',
    },
    {
        banner: "https://as1.ftcdn.net/v2/jpg/04/35/10/18/1000_F_435101823_jottowrJG1OG4gbM2r26VTrvxFSg8yBi.jpg",
        video: "SyVMma1IkXM",
        id: 4,
        title: "Blockchain in 4 Hrs",
        tutor: "Sandeep: Simplilearn",
        likes: "3.4 k",
        views: "1.7 L",
        duration: "4 Hrs",
    },
    {
        banner: "https://www.webmarketing-com.com/wp-content/uploads/2022/06/alternative-photoshop-1024x576.jpg.webp",
        video: "IyR_uYsRdPs",
        id: 6,
        title: "Photoshop for Beginners",
        tutor: "Dan Scott",
        likes: "2.4 L",
        views: "1.2 C",
        duration: "3 Hrs",
    },
    {
        banner: "https://www.simplilearn.com/ice9/free_resources_article_thumb/what_is_Data_Science.jpg",
        video: "d0bIgigcOQM",
        id: 7,
        title: "Full Data Science Course",
        tutor: "Rune",
        likes: "12 k",
        views: "6.6 L",
        duration: "12 Hrs",
    },
    {
        banner: "https://i.ytimg.com/vi/7C4dv8vuwEk/maxresdefault.jpg",
        video: "zJSY8tbf_ys",
        id: 10,
        title: "Frontend Development Bootcamp",
        tutor: "Zach Golwitzer",
        likes: "38 k",
        views: "9.9 L",
        duration: "12.25 Hrs",
    },
]

export { allVideos, allFeaturedVideos};