const allVideos = [
    {
        banner: null,
        video: null,
        id: 1,
        title: "Python Course for Beginners",
        tutor: null,
        likes: null,
        views: null,
    },
    {
        banner: null,
        video: null,
        id: 2,
        title: "Java for Beginners",
        tutor: null,
        likes: null,
        views: null,
    },
    {
        banner: null,
        video: null,
        id: 3,
        title: "Learning Blender from Scratch",
        tutor: null,
        likes: null,
        views: null,
    },
    {
        banner: null,
        video: null,
        id: 4,
        title: "Blockchain in 4 Hours",
        tutor: null,
        likes: null,
        views: null,
    },
    {
        banner: null,
        video: null,
        id: 5,
        title: "React Native: from Zero to Hero",
        tutor: "Mahdi Sharifimehr",
        likes: "8.6 k",
        views: "5.1 L",
    },
    {
        banner: null,
        video: null,
        id: 6,
        title: "Photoshop for Beginners",
        tutor: null,
        likes: null,
        views: null,
    },
    {
        banner: null,
        video: null,
        id: 7,
        title: "Full Stack Web Development in 10 Hrs",
        tutor: null,
        likes: null,
        views: null,
    },
    {
        banner: null,
        video: null,
        id: 8,
        title: "Basics of Stock Market for beginners",
        tutor: null,
        likes: null,
        views: null,
    },
    {
        banner: null,
        video: null,
        id: 9,
        title: "Ethical Hacking in 12 Hrs",
        tutor: null,
        likes: null,
        views: null,
    },
]
const featuredVideos = [
    {
        banner: "https://i.ytimg.com/vi/XKHEtdqhLK8/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBAjfK92LmwESwPBTNq29J1xNmuHg",
        video: null,
        id: 1,
        title: "Python Course for Beginners",
        tutor: "Chris: Bro Code",
        likes: "4.2 L",
        views: "81 L",
    },
    {
        banner: "https://i.ytimg.com/vi/SyVMma1IkXM/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDsjsrGGGFagNjx6IKoZAuZ_uARTg",
        video: null,
        id: 2,
        title: "Blockchain in 4 Hours",
        tutor: "Sandeep: Simplilearn",
        likes: "3.4 k",
        views: "1.7 L",
    },
    {
        banner: "https://process.fs.teachablecdn.com/ADNupMnWyR7kCWRvm76Laz/resize=width:705/https://www.filepicker.io/api/file/4C6yPDywSUeWYLyg1h9G",
        video: null,
        id: 3,
        title: "React Native: from Zero to Hero",
        tutor: "Mahdi Sharifimehr",
        likes: "8.6 k",
        views: "5.1 L",
    },
]

export {allVideos, featuredVideos};